### ISSUE TITLE
Please explain "goodpassword" as used in README.md

### ISSUE THREAD

**Issue by rainabba** [mhdawson/google-drive-wrapper#2]
```README.md
"of course use your own passwords, not the ones shown!"
and 
var wrapper = new gdriveWrapper(auth, google, 'goodpassword');
```

**Comment by mhdawson** [comment]
You need to use your google drive password instead of 'goodpassword' is what it means. (Edited, this was incorrect, see comments below)

**Comment by rainabba** [comment]
Sorry, don't mean to be dense here, but you mean my personal Google password? I'm building this for a node.js service and largely because your google-auth-wrapper looked like it was a very clean implementation and this depended on it.

**Comment by rainabba** [comment]
Decided to think rather than bug you more than needed :)

Looking at https://github.com/mhdawson/google-drive-wrapper/blob/master/lib/gdriveWrapper.js#L48, I'm now thinking that password is only for encrypting/decrypting files in flight and I can omit if I'm not encrypting in flight because it has nothing to do with Drive and would infact create issues with using the file inside Drive (opening on the web, desktop, etc..) yes?

**Comment by mhdawson** [comment]
You could be correct, its been a while since I wrote this.  You do need to authenticate, but you are likely correct that its for the encryption part.

**Comment by mhdawson** [comment]
The encryption in flight is just for things you don't trust to expose to google :)

When I use the wrapper for creating issues for the Node.js community meetings they are not encrypted.

**Comment by rainabba** [comment]
Just added a minor PR here to add info I would have found helpful in README.md

https://github.com/mhdawson/google-drive-wrapper/pull/3
